# Generated by Django 5.0.2 on 2024-03-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='one_to_many_relation1',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='one_to_many_relation',
            new_name='post',
        ),
    ]
