# Generated by Django 5.0.2 on 2024-03-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_rename_one_to_many_relation1_postcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='one_to_many_relation_posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='one_to_many_relation1',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='one_to_many_relation',
            new_name='author',
        ),
    ]
